Simple DEMO for vesting schedule
blastroyale/blast-royale-contracts pull request #13
Opened 2022-05-05 09:27 UTC by JensonCollins

2022-05-05 10:34 UTC, mrfungfung requested changes

2022-05-05 10:34 UTC, mrfungfung commented on contracts/Vesting/TokenVesting.sol
> +    function createVestingSchedule(
When we create a vesting schedule - there is actually an initial amount of coins that are immediately given to the beneficiary. We can call this _immediateReleaseAmount

2022-05-05 10:34 UTC, mrfungfung commented on contracts/Vesting/TokenVesting.sol
> +    /// <=============== VIEWS ===============>
We also need to add a "revoke" function that removes a vesting schedule

2022-05-05 10:34 UTC, mrfungfung commented on contracts/Vesting/TokenVesting.sol
> +    struct VestingSchedule {
We need to change the VestingSchedule a bit to do this kind of calculation:

Let's take Private Sale vesting "4% unlocked at the TGE, then 6 months cliff, then unlock 4% more each month"
Imagine that our TGE is in January.
So the process will be:
In January we give them 4% and we start counting the cliff
February, March, April, May, June - no more tokens. So January-to-June = 6 months cliff
In July we give 4% more
In August we give 4% more
etc.
With Advisors - "0% unlocked at the TGE, then 9 months cliff, then 2% unlocked each month":
In January we give them nothing and we start counting the cliff
February, March, April, May, June, July, August, September - no more tokens. So January-to-September = 9 months cliff
In October we give 2% of tokens
In November we give 2% more
etc.
And a special case when we unlock some weird percentage every month that won't add up to 100.
Imagine we have vesting "30% at TGE then 30% more each month"
So the process will be:
January at TGE we give 30%
February - 30% more
March - 30% more
April - we give the remaining 10%

So - the amount given at TGE = _immediateReleaseAmount, but then the remaining is going to be calculated differently. Just take a look at the comment in release()

2022-05-05 10:34 UTC, mrfungfung commented on contracts/Vesting/TokenVesting.sol
> +            uint256 timeFromStart = currentTime.sub(vestingSchedule.start);
We change this to

uint256 timeFromStart = currentTime.sub(vestingSchedule.cliffStart);

2022-05-05 15:37 UTC, mrfungfung requested changes

2022-05-05 15:37 UTC, mrfungfung commented on contracts/Vesting/TokenVesting.sol
>              _amount,
Rename to _amountTotal

2022-05-05 15:37 UTC, mrfungfung commented on contracts/Vesting/TokenVesting.sol
> +        // Transfer TGE
Remove this. Let the user get it manually by calling release()

2022-05-05 15:46 UTC, mrfungfung commented on contracts/Vesting/TokenVesting.sol
> +    uint public constant DECIMAL_FACTOR = 10 ** 6;
Delete this....I dont see it used?

2022-05-05 15:48 UTC, JensonCollins commented on contracts/Vesting/TokenVesting.sol
> +    uint public constant DECIMAL_FACTOR = 10 ** 6;
I think it will be used in future development. Let me keep it in comments

2022-05-06 12:34 UTC, mrfungfung commented on contracts/Vesting/TokenVesting.sol
> +        uint256 vestedAmount = _computeReleasableAmount(vestingSchedule);
Rename vestedAmount to releasableAmount

2022-05-06 19:19 UTC, merged